package typegen

import (
	"fmt"
	"go/format"
	"go/token"
	"strconv"
	"strings"

	"github.com/capydatabase/capydbclient"
)

// GoFilename is the default output file for GenerateGo.
const GoFilename = "models.go"

var goTypeByUDT = map[string]string{
	"int2": "int16", "int4": "int32", "int8": "int64", "oid": "uint32",
	"float4": "float32", "float8": "float64",
	"bool":  "bool",
	"bytea": "[]byte",
	"json":  "json.RawMessage", "jsonb": "json.RawMessage",
	"date": "time.Time", "timestamp": "time.Time", "timestamptz": "time.Time",
}

// Types whose wire text is the natural Go value. numeric and money stay
// strings: float64 would silently lose precision.
var goStringUDTs = map[string]struct{}{
	"numeric": {}, "money": {},
	"text": {}, "varchar": {}, "bpchar": {}, "char": {}, "name": {}, "citext": {},
	"uuid": {}, "inet": {}, "cidr": {}, "macaddr": {}, "macaddr8": {},
	"bit": {}, "varbit": {}, "xml": {},
	"time": {}, "timetz": {}, "interval": {},
	"tsvector": {}, "tsquery": {},
	"point": {}, "line": {}, "lseg": {}, "box": {}, "path": {}, "polygon": {}, "circle": {},
}

// goInitialisms are the words Go naming conventions keep upper case
// (UserID, not UserId).
var goInitialisms = map[string]bool{
	"api": true, "db": true, "html": true, "http": true, "https": true, "id": true, "ip": true,
	"json": true, "sql": true, "ssl": true, "tls": true, "uid": true, "uri": true, "url": true,
	"uuid": true, "xml": true,
}

// goName renders an exported Go identifier. Unlike pascalCase it also splits
// camelCase humps, so userId and user_id both become UserID.
func goName(name string) string {
	result := goWords(name)
	if result[0] >= '0' && result[0] <= '9' {
		return "T" + result
	}
	return result
}

// goWords joins the words of name in Go casing without the leading-digit
// guard, for names that are appended to an existing identifier.
func goWords(name string) string {
	var b strings.Builder
	for _, word := range splitCamelWords(name) {
		lower := strings.ToLower(word)
		if goInitialisms[lower] {
			b.WriteString(strings.ToUpper(lower))
			continue
		}
		b.WriteString(strings.ToUpper(word[:1]))
		b.WriteString(strings.ToLower(word[1:]))
	}
	return b.String()
}

// splitCamelWords splits on non-alphanumerics and on lower-to-upper case
// transitions.
func splitCamelWords(name string) []string {
	words := []string{}
	for _, part := range splitWords(name) {
		start := 0
		for i := 1; i < len(part); i++ {
			if part[i] >= 'A' && part[i] <= 'Z' && part[i-1] >= 'a' && part[i-1] <= 'z' {
				words = append(words, part[start:i])
				start = i
			}
		}
		words = append(words, part[start:])
	}
	return words
}

// ValidGoPackage reports whether name can be used as a package clause.
func ValidGoPackage(name string) bool {
	return token.IsIdentifier(name) && !token.IsKeyword(name) && name != "_"
}

type goGenerator struct {
	enums     map[enumKey]capydbclient.SchemaEnum
	enumNames map[enumKey]string
	usesJSON  bool
	usesTime  bool
	topLevel  nameSet
}

// GenerateGo renders one Go file: a string type plus constants per enum, and
// per relation a row struct (db and json tags carry the column names) with
// constants for the relation and column names. Nullable columns are
// pointers; nil slices, []byte and json.RawMessage already carry NULL.
// Columns of a type the generator does not know are typed any.
func GenerateGo(schema capydbclient.DatabaseSchema, packageName string) (string, error) {
	if !ValidGoPackage(packageName) {
		return "", fmt.Errorf("invalid Go package name %q", packageName)
	}
	g := &goGenerator{
		enums:     collectEnums(schema),
		enumNames: map[enumKey]string{},
		topLevel:  nameSet{},
	}

	var body strings.Builder
	namespaces := sortedNamespaces(schema)
	for _, namespace := range namespaces {
		for _, enum := range namespace.Enums {
			g.writeEnum(&body, namespace.Name, enum)
		}
	}
	for _, namespace := range namespaces {
		for _, table := range namespace.Tables {
			g.writeRelation(&body, namespace.Name, table)
		}
	}

	var out strings.Builder
	out.WriteString("// Code generated by capydb generate go from the live database schema. DO NOT EDIT.\n")
	out.WriteString("// Regenerate with: capydb generate go\n\n")
	fmt.Fprintf(&out, "package %s\n", packageName)
	imports := []string{}
	if g.usesJSON {
		imports = append(imports, `"encoding/json"`)
	}
	if g.usesTime {
		imports = append(imports, `"time"`)
	}
	switch len(imports) {
	case 0:
	case 1:
		fmt.Fprintf(&out, "\nimport %s\n", imports[0])
	default:
		out.WriteString("\nimport (\n")
		for _, path := range imports {
			fmt.Fprintf(&out, "\t%s\n", path)
		}
		out.WriteString(")\n")
	}
	out.WriteString(body.String())
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return "", fmt.Errorf("format generated Go: %w", err)
	}
	return string(formatted), nil
}

func (g *goGenerator) writeEnum(b *strings.Builder, schemaName string, enum capydbclient.SchemaEnum) {
	typeName := g.topLevel.claim(typePrefix(schemaName) + goName(enum.Name))
	g.enumNames[enumKey{schema: schemaName, name: enum.Name}] = typeName

	fmt.Fprintf(b, "\n// %s is the %s.%s enum.\n", typeName, commentText(schemaName), commentText(enum.Name))
	fmt.Fprintf(b, "type %s string\n", typeName)
	if len(enum.Values) == 0 {
		return
	}
	b.WriteString("\nconst (\n")
	for _, value := range enum.Values {
		constName := g.topLevel.claim(typeName + goWords(value))
		fmt.Fprintf(b, "\t%s %s = %s\n", constName, typeName, strconv.Quote(value))
	}
	b.WriteString(")\n")
}

func (g *goGenerator) writeRelation(b *strings.Builder, schemaName string, table capydbclient.SchemaTable) {
	base := typePrefix(schemaName) + goName(table.Name)
	typeName := g.topLevel.claim(base + "Row")
	kind := "table"
	if !isTableKind(table.Kind) {
		kind = strings.ReplaceAll(table.Kind, "_", " ")
	}

	fmt.Fprintf(b, "\n// %s is a row of the %s %s.%s.\n", typeName, kind, commentText(schemaName), commentText(table.Name))
	if strings.TrimSpace(table.Comment) != "" {
		fmt.Fprintf(b, "//\n// %s\n", commentText(table.Comment))
	}
	fmt.Fprintf(b, "type %s struct {\n", typeName)
	fields := nameSet{}
	for _, column := range table.Columns {
		field := fields.claim(goName(column.Name))
		line := fmt.Sprintf("\t%s %s %s", field, g.columnType(column), goStructTag(column.Name))
		if strings.TrimSpace(column.Comment) != "" {
			line += " // " + commentText(column.Comment)
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("}\n")

	b.WriteString("\nconst (\n")
	fmt.Fprintf(b, "\t%s = %s\n", g.topLevel.claim(base+"Schema"), strconv.Quote(schemaName))
	fmt.Fprintf(b, "\t%s = %s\n", g.topLevel.claim(base+"Table"), strconv.Quote(table.Name))
	for _, column := range table.Columns {
		fmt.Fprintf(b, "\t%s = %s\n", g.topLevel.claim(base+"Column"+goWords(column.Name)), strconv.Quote(column.Name))
	}
	b.WriteString(")\n")
}

func (g *goGenerator) baseType(column capydbclient.SchemaColumn) string {
	if column.IsEnum {
		if name, ok := g.enumNames[enumKey{schema: column.UDTSchema, name: column.UDTName}]; ok {
			return name
		}
		return "string"
	}
	if mapped, ok := goTypeByUDT[column.UDTName]; ok {
		switch mapped {
		case "json.RawMessage":
			g.usesJSON = true
		case "time.Time":
			g.usesTime = true
		}
		return mapped
	}
	if _, ok := goStringUDTs[column.UDTName]; ok {
		return "string"
	}
	return "any"
}

func (g *goGenerator) columnType(column capydbclient.SchemaColumn) string {
	base := g.baseType(column)
	if column.IsArray {
		return strings.Repeat("[]", arrayDims(column)) + base
	}
	if column.IsNullable && !goNilable(base) {
		return "*" + base
	}
	return base
}

// goNilable reports whether the zero value already represents SQL NULL.
func goNilable(goType string) bool {
	return goType == "any" || goType == "[]byte" || goType == "json.RawMessage"
}

// goStructTag renders the db/json tag. Column names are user-controlled, so
// each value is a quoted Go string (reflect.StructTag unquotes it), and the
// whole tag falls back to an interpreted literal if a backtick shows up.
func goStructTag(column string) string {
	content := "db:" + strconv.Quote(column)
	// encoding/json reads a comma as the start of the tag options, so a
	// column name containing one keeps only its db tag (json falls back to
	// the field name).
	if !strings.Contains(column, ",") {
		content += " json:" + strconv.Quote(column)
	}
	if strings.Contains(content, "`") {
		return strconv.Quote(content)
	}
	return "`" + content + "`"
}
