package typegen

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/capydatabase/capydbclient"
)

// PythonFilename is the default output file for GeneratePython.
const PythonFilename = "models.py"

// Python output styles.
const (
	PythonStyleDataclass = "dataclass"
	PythonStylePydantic  = "pydantic"
)

// Python types follow what psycopg 3 returns for each column type, so an
// annotation never claims a value the driver will not produce. Types psycopg
// loads into objects outside the standard library shapes used here (network
// addresses load as ipaddress objects of several classes) are typed Any.
var pythonTypeByUDT = map[string]string{
	"int2": "int", "int4": "int", "int8": "int", "oid": "int",
	"float4": "float", "float8": "float",
	"numeric": "decimal.Decimal",
	"bool":    "bool",
	"bytea":   "bytes",
	"uuid":    "uuid.UUID",
	"json":    "Any", "jsonb": "Any",
	"date": "datetime.date", "timestamp": "datetime.datetime", "timestamptz": "datetime.datetime",
	"time": "datetime.time", "timetz": "datetime.time", "interval": "datetime.timedelta",
}

var pythonStringUDTs = map[string]struct{}{
	"money": {},
	"text":  {}, "varchar": {}, "bpchar": {}, "char": {}, "name": {}, "citext": {},
	"macaddr": {}, "macaddr8": {}, "bit": {}, "varbit": {}, "xml": {},
	"tsvector": {}, "tsquery": {},
}

var pythonKeywords = map[string]bool{
	"False": true, "None": true, "True": true, "and": true, "as": true, "assert": true, "async": true,
	"await": true, "break": true, "class": true, "continue": true, "def": true, "del": true, "elif": true,
	"else": true, "except": true, "finally": true, "for": true, "from": true, "global": true, "if": true,
	"import": true, "in": true, "is": true, "lambda": true, "nonlocal": true, "not": true, "or": true,
	"pass": true, "raise": true, "return": true, "try": true, "while": true, "with": true, "yield": true,
}

var pythonIdentifier = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// pythonFieldName returns an attribute name for a column and whether it had
// to be changed (keyword, or characters Python identifiers cannot hold).
func pythonFieldName(column string) (string, bool) {
	if pythonIdentifier.MatchString(column) && !pythonKeywords[column] {
		return column, false
	}
	if pythonIdentifier.MatchString(column) {
		return column + "_", true
	}
	name := strings.ToLower(strings.Join(splitWords(column), "_"))
	if name[0] >= '0' && name[0] <= '9' {
		name = "c_" + name
	}
	if pythonKeywords[name] {
		name += "_"
	}
	return name, true
}

func pythonEnumMember(value string) string {
	name := strings.ToUpper(strings.Join(splitWords(value), "_"))
	if name[0] >= '0' && name[0] <= '9' {
		name = "V_" + name
	}
	return name
}

// pythonString renders a double-quoted Python literal. strconv.Quote's escapes
// (\n, \t, \", \\, \xNN, \uNNNN, \UNNNNNNNN) are all valid in Python strings.
func pythonString(value string) string {
	return strconv.Quote(value)
}

type pythonGenerator struct {
	enums     map[enumKey]capydbclient.SchemaEnum
	enumNames map[enumKey]string
	imports   map[string]bool
	topLevel  nameSet
	style     string
}

// GeneratePython renders one module: a str Enum per enum type and per
// relation either a frozen dataclass (style "dataclass", standard library
// only) or a pydantic model (style "pydantic"). Nullable columns are
// `T | None`; arrays are nested lists. Columns whose name is not a valid
// Python identifier get a sanitized attribute name - pydantic models keep the
// column name as the field alias, dataclasses note it in a comment.
func GeneratePython(schema capydbclient.DatabaseSchema, style string) (string, error) {
	if style == "" {
		style = PythonStyleDataclass
	}
	if style != PythonStyleDataclass && style != PythonStylePydantic {
		return "", fmt.Errorf("python style must be %s or %s", PythonStyleDataclass, PythonStylePydantic)
	}
	g := &pythonGenerator{
		enums:     collectEnums(schema),
		enumNames: map[enumKey]string{},
		imports:   map[string]bool{},
		topLevel:  nameSet{},
		style:     style,
	}

	var body strings.Builder
	namespaces := sortedNamespaces(schema)
	for _, namespace := range namespaces {
		for _, enum := range namespace.Enums {
			g.writeEnum(&body, namespace.Name, enum)
		}
	}
	for _, namespace := range namespaces {
		for _, table := range namespace.Tables {
			g.writeRelation(&body, namespace.Name, table)
		}
	}

	var out strings.Builder
	out.WriteString("# Generated by CapyDB from the live database schema. Do not edit by hand.\n")
	out.WriteString("# Regenerate with: capydb generate python\n\n")
	out.WriteString("from __future__ import annotations\n\n")
	for _, module := range []string{"datetime", "decimal", "uuid"} {
		if g.imports[module] {
			fmt.Fprintf(&out, "import %s\n", module)
		}
	}
	if style == PythonStyleDataclass {
		out.WriteString("from dataclasses import dataclass\n")
	}
	if g.imports["enum"] {
		out.WriteString("from enum import Enum\n")
	}
	out.WriteString("from typing import Any, ClassVar\n")
	if style == PythonStylePydantic {
		if g.imports["Field"] {
			out.WriteString("\nfrom pydantic import BaseModel, ConfigDict, Field\n")
		} else {
			out.WriteString("\nfrom pydantic import BaseModel, ConfigDict\n")
		}
	}
	out.WriteString(body.String())
	return out.String(), nil
}

func (g *pythonGenerator) writeEnum(b *strings.Builder, schemaName string, enum capydbclient.SchemaEnum) {
	g.imports["enum"] = true
	className := g.topLevel.claim(typePrefix(schemaName) + pascalCase(enum.Name))
	g.enumNames[enumKey{schema: schemaName, name: enum.Name}] = className

	fmt.Fprintf(b, "\n\nclass %s(str, Enum):\n", className)
	fmt.Fprintf(b, "    \"\"\"The %s.%s enum.\"\"\"\n", pythonDocText(schemaName), pythonDocText(enum.Name))
	if len(enum.Values) == 0 {
		b.WriteString("\n    pass\n")
		return
	}
	b.WriteString("\n")
	members := nameSet{}
	for _, value := range enum.Values {
		fmt.Fprintf(b, "    %s = %s\n", members.claim(pythonEnumMember(value)), pythonString(value))
	}
}

func (g *pythonGenerator) writeRelation(b *strings.Builder, schemaName string, table capydbclient.SchemaTable) {
	className := g.topLevel.claim(typePrefix(schemaName) + pascalCase(table.Name) + "Row")
	kind := "table"
	if !isTableKind(table.Kind) {
		kind = strings.ReplaceAll(table.Kind, "_", " ")
	}

	b.WriteString("\n\n")
	if g.style == PythonStyleDataclass {
		b.WriteString("@dataclass(frozen=True)\n")
		fmt.Fprintf(b, "class %s:\n", className)
	} else {
		fmt.Fprintf(b, "class %s(BaseModel):\n", className)
	}
	doc := fmt.Sprintf("A row of the %s %s.%s.", kind, pythonDocText(schemaName), pythonDocText(table.Name))
	if strings.TrimSpace(table.Comment) != "" {
		doc += "\n\n    " + pythonDocText(table.Comment) + "\n    "
	}
	fmt.Fprintf(b, "    \"\"\"%s\"\"\"\n\n", doc)
	if g.style == PythonStylePydantic {
		b.WriteString("    model_config = ConfigDict(frozen=True, populate_by_name=True)\n\n")
	}

	fields := nameSet{"SCHEMA": true, "TABLE": true, "model_config": true}
	for _, column := range table.Columns {
		fieldName, renamed := pythonFieldName(column.Name)
		fieldName = fields.claim(fieldName)
		renamed = renamed || fieldName != column.Name
		annotation := g.columnType(column)
		commentBody := commentText(column.Comment)
		comment := ""
		if strings.TrimSpace(commentBody) != "" {
			comment = "  # " + commentBody
		}
		switch {
		case renamed && g.style == PythonStylePydantic:
			g.imports["Field"] = true
			fmt.Fprintf(b, "    %s: %s = Field(alias=%s)%s\n", fieldName, annotation, pythonString(column.Name), comment)
		case renamed:
			note := "  # column " + pythonString(column.Name)
			if strings.TrimSpace(commentBody) != "" {
				note += "; " + commentBody
			}
			fmt.Fprintf(b, "    %s: %s%s\n", fieldName, annotation, note)
		default:
			fmt.Fprintf(b, "    %s: %s%s\n", fieldName, annotation, comment)
		}
	}
	if len(table.Columns) > 0 {
		b.WriteString("\n")
	}
	fmt.Fprintf(b, "    SCHEMA: ClassVar[str] = %s\n", pythonString(schemaName))
	fmt.Fprintf(b, "    TABLE: ClassVar[str] = %s\n", pythonString(table.Name))
}

func (g *pythonGenerator) baseType(column capydbclient.SchemaColumn) string {
	if column.IsEnum {
		if name, ok := g.enumNames[enumKey{schema: column.UDTSchema, name: column.UDTName}]; ok {
			return name
		}
		return "str"
	}
	if mapped, ok := pythonTypeByUDT[column.UDTName]; ok {
		if module, _, found := strings.Cut(mapped, "."); found {
			g.imports[module] = true
		}
		return mapped
	}
	if _, ok := pythonStringUDTs[column.UDTName]; ok {
		return "str"
	}
	return "Any"
}

func (g *pythonGenerator) columnType(column capydbclient.SchemaColumn) string {
	annotation := g.baseType(column)
	if column.IsArray {
		for range arrayDims(column) {
			annotation = "list[" + annotation + "]"
		}
	}
	if column.IsNullable && annotation != "Any" {
		annotation += " | None"
	}
	return annotation
}

// pythonDocText keeps catalog text inside a one-line docstring: no line
// terminators, and every quote escaped so nothing can close the triple quote
// (including a trailing quote that would merge with the closing one).
func pythonDocText(value string) string {
	value = commentText(value)
	value = strings.ReplaceAll(value, `\`, `\\`)
	return strings.ReplaceAll(value, `"`, `\"`)
}
